apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: lynx2-trigger-binding
spec:
  params:
    - name: namespace
      value: lynx2-dev
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
