apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: lynx2-dev
secrets:
  - name: github-pat-secret
  - name: quay-io-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - list
      - patch
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer
subjects:
  - kind: ServiceAccount
    name: build-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   creationTimestamp: null
#   name: cluster-admin
#   namespace: lynx2-dev
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: build-bot
#   namespace: lynx2-dev